{% set name = "seekpath" %}
{% set version = "1.9.3" %}
{% set sha256 = "abc806479f11e7f71c4475a292d849baf15dfa1cbc89ecc602d78415de322c83" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python
  run:
    - python
    - future >=0.15
    - numpy >=1.0
    - spglib >=1.9.4

test:
  imports:
    - seekpath
    - seekpath.brillouinzone
    - seekpath.hpkot

about:
  home: http://github.com/giovannipizzi/seekpath
  license: MIT
  license_family: MIT
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE.txt' 
  summary: "A module to obtain and visualize k-vector coefficients and obtain band paths in the Brillouin zone of crystal structures."

extra:
  recipe-maintainers:
    - npavlovikj
